name: Stable Compilation

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  docker:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:10     # CMake 3.13.4 - g++ 8.3.0  - oldstable
          - ubuntu:20.04  # CMake 3.16.3 - g++ 9.3.0  - LTS
          - debian:11     # CMake 3.18.4 - g++ 10.2.1 - stable
          - ubuntu:22.04  # CMake 3.22.1 - g++ 11.2.0 - LTS
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt-get update
          apt-get install -y --no-install-recommends --no-install-suggests \
            build-essential cmake ninja-build git \
            libicu-dev libexpat1-dev

      - name: Compile
        run: |
          cmake -G Ninja -B build . \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
          cmake --build build

      - name: Install
        run: |
          export DESTDIR=$PWD/local-install
          # cmake < 3.16 does not support '--install'
          cmake --build build --target install

      - name: Test
        run: cmake --build build --target check
